remote_theme: pages-themes/minimal@v0.2.0

title: [The title of your site]
description: [A short description of your site]
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
